[2025-08-03T00:25:24.462+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_nyc_taxi_etl.validate_data scheduled__2025-08-02T18:25:20.064022+00:00 [queued]>
[2025-08-03T00:25:24.466+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_nyc_taxi_etl.validate_data scheduled__2025-08-02T18:25:20.064022+00:00 [queued]>
[2025-08-03T00:25:24.466+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-08-03T00:25:24.550+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): validate_data> on 2025-08-02 18:25:20.064022+00:00
[2025-08-03T00:25:24.555+0000] {standard_task_runner.py:57} INFO - Started process 967 to run task
[2025-08-03T00:25:24.562+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple_nyc_taxi_etl', 'validate_data', 'scheduled__2025-08-02T18:25:20.064022+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/simple_nyc_taxi_etl.py', '--cfg-path', '/tmp/tmp58pg_7w4']
[2025-08-03T00:25:24.566+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask validate_data
[2025-08-03T00:25:24.598+0000] {task_command.py:415} INFO - Running <TaskInstance: simple_nyc_taxi_etl.validate_data scheduled__2025-08-02T18:25:20.064022+00:00 [running]> on host 6fb539098074
[2025-08-03T00:25:24.642+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering' AIRFLOW_CTX_DAG_ID='simple_nyc_taxi_etl' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T18:25:20.064022+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-02T18:25:20.064022+00:00'
[2025-08-03T00:25:24.651+0000] {logging_mixin.py:151} INFO - Data validation passed. 1000 records ready for processing.
[2025-08-03T00:25:24.652+0000] {python.py:194} INFO - Done. Returned value was: True
[2025-08-03T00:25:24.662+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=simple_nyc_taxi_etl, task_id=validate_data, execution_date=20250802T182520, start_date=20250803T002524, end_date=20250803T002524
[2025-08-03T00:25:24.701+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T00:25:24.711+0000] {taskinstance.py:2776} INFO - 2 downstream tasks scheduled from follow-on schedule check
